---
title: "Visualization"
author: "Yaduo Wang"
date: "2023-09-28"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

weather_df
```

Let's make a plot.

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + geom_point()
```

#Fancy plot
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)+
  geom_smooth(se = FALSE)

```

plot facets

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)+
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

Let's try a different plot. temps are boring. 

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size=prcp), alpha = .5)+
  geom_smooth(se = FALSE)+
  facet_grid(. ~ name)
```

try assigning specific color

```{r}
weather_df |> 
  filter(name != "CentralPark_NY") |> 
  ggplot(aes(x=date, y=tmax, color = name)) + 
  geom_point(size = .7, alpha = .5,)
```

hex_plot
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_hex()
```

##Univariate plotting

histogram
```{r}
weather_df |> 
  ggplot(aes(x = tmax, fill = name)) + 
  geom_histogram(position = "dodge")
```

Let's use a density plot.
```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + 
  geom_density(alpha = .3, adjust = 2)
```

boxplot

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_boxplot()
```

violin plot

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), alpha = .5) + 
  stat_summary(fun = "median", color = "blue")
```

ridge plot
```{r}
ggplot(weather_df, aes(x = tmax, y = name)) + 
  geom_density_ridges(scale = .85)
```

##saving and embedding plots

```{r}
geom_weather = 
  ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
geom_weather
ggsave("geom_weather.pdf", geom_weather, width = 8, height = 5)
```

```{r, fig.width = 3, fig.asp = .6}
geom_weather
```

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

